CREATE TABLE todos (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  activity_group_id BIGINT DEFAULT NULL,
  title VARCHAR(255) DEFAULT NULL,
  is_active INTEGER DEFAULT NULL,
  priority VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
);